### ISSUE TITLE
Results do not match Lumerical

### ISSUE THREAD

**Issue by simbilod** [simbilod/grating_coupler_meep#4]
This issue tracks efforts to resolve the discrepancy between the MEEP solver and Lumerical

**Comment by simbilod** [comment]
I've been improving the visualization tools, and this is what I am getting for the index distribution @joamatab

Legend:
Red -- n=1.44 (nSiO2)
Green -- n=1.446 (ncoreFiber)
Blue -- n = 3.48 (nSi)

I'll tidy up the plotting tool, then work on updating the simulation geometry.

![image](https://user-images.githubusercontent.com/46427609/142274395-eb6e947d-42ea-48e3-94b3-35c26c79f847.png)

**Comment by joamatab** [comment]
looks great Simon

Something that concerns me is that the fiber angle does not affect the spectrum shape

I swept more wavelengths and start to see the transmission peak

![image](https://user-images.githubusercontent.com/4514346/144365342-c7388e28-7fa8-4d97-8fef-10d6292bdeea.png)

**Comment by simbilod** [comment]
Good to know. 

I am taking some time to look at this today, but from the further updated visualization we may also be having port issues (source is black, gray is monitors -- looks like the fiber mode won't be solved for properly). 

I'll push what I have on dev, but still want to add directionality arrows to the ports and movie options to help troubleshoot

![image](https://user-images.githubusercontent.com/46427609/144468350-2b74af7b-dce8-4f75-b2de-50c1f06b66cf.png)

**Comment by joamatab** [comment]
See related issue in

https://github.com/NanoComp/meep/issues/1838

**Comment by simbilod** [comment]
Animations generated outside of the simulation run take forever, so I am building this functionality in the source code for troubleshooting. See [NanoComp/meep/pull/1867](https://github.com/NanoComp/meep/pull/1867)

**Comment by simbilod** [comment]
I have narrowed the issue down to how the fiber port mode is being resolved. Need to investigate whether it is an index contrast issue (double check fiber index or port size, although I've already made the port as large as Lumerical's) or bad k-vector selection (since it is an oblique waveguide).

See e.g. waveguide port nicely localized:

![waveguide](https://user-images.githubusercontent.com/46427609/147986159-356ce859-9121-4e04-8a46-0d39f332f123.png)

Whereas fiber port:

![fiber](https://user-images.githubusercontent.com/46427609/147986194-0c2ef2be-c8f8-4015-b2b9-29ebb1093c1c.png)

**Comment by simbilod** [comment]
By ensuring that the fiber monitors is monitoring the suitable mode:

![image](https://user-images.githubusercontent.com/46427609/148710554-bcb80d8f-239a-47b3-a98f-4d4a2ba1fcf1.png)

We are able to get order-of-magnitude agreement with Lumerical:

![image](https://user-images.githubusercontent.com/46427609/148710517-8ad61346-c270-4960-8d27-8ffa72ef4fc9.png)

There may be more work to be done to get an exact match, but this is probably just ensuring an identical simulation/materials/etc.
